// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pruneEdgesHelper
IntegerVector pruneEdgesHelper(IntegerVector support, IntegerMatrix edgeList, int numLeaves, int numVertices);
RcppExport SEXP sBIC_pruneEdgesHelper(SEXP supportSEXP, SEXP edgeListSEXP, SEXP numLeavesSEXP, SEXP numVerticesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type support(supportSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type edgeList(edgeListSEXP);
    Rcpp::traits::input_parameter< int >::type numLeaves(numLeavesSEXP);
    Rcpp::traits::input_parameter< int >::type numVertices(numVerticesSEXP);
    __result = Rcpp::wrap(pruneEdgesHelper(support, edgeList, numLeaves, numVertices));
    return __result;
END_RCPP
}
