# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pruneEdgesHelper <- function(support, edgeList, numLeaves, numVertices) {
    .Call('sBIC_pruneEdgesHelper', PACKAGE = 'sBIC', support, edgeList, numLeaves, numVertices)
}

